name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "tpc-pascal"
          git config --global user.email "tpcmemory2005@gmail.com"
          git push --force https://tpc-pascal:$HF_TOKEN@huggingface.co/spaces/tpc-pascal/subpas $(git subtree split --prefix hf main):main
